### ISSUE TITLE
Prompt to deploy Firebase Functions

### ISSUE THREAD

**Issue by AntonioStipic** [Jaspero/cli#1]
Upon successful execution of setup (Step `Run Setup script?`), prompt once again with `Do you want to run initial deploy of Firebase Functions?`.
If true, using `fs` enter directory `{projectName}/functions` and run:
- `npm i`
- `npm run deploy`

**Comment by julian-King22** [comment]
Can you please give more discription

**Comment by AntonioStipic** [comment]
@AviatorIfeanyi Updated issue with description. Thank you for your comment! :smiley:
